#!/usr/bin/env bash
# fw.sh — one recipe, four backends (iptables, nftables, ufw, firewalld).
#
#   sudo ./fw.sh recipes/web-server.conf                # apply; autodetects ufw > firewalld > nftables > iptables
#   sudo ./fw.sh recipes/steam-server.conf -t nftables  # pick a backend
#        ./fw.sh recipes/ssh-allowlist.conf -t ufw -n   # -n: print what would run, touch nothing
#
# A recipe is a shell fragment with two variables:
#   ALLOW="22/tcp@203.0.113.0/24 80/tcp 443/tcp 27015:27030/udp"   # port[:range]/proto, optional @cidr
#   PING=yes
# Policy is always: inbound drop except ALLOW + loopback + established; outbound open; v4 and v6.
set -euo pipefail

RECIPE="${1:-}" TOOL="" DRY=0
[[ -n "$RECIPE" && -f "$RECIPE" ]] || { sed -n '2,12p' "$0" >&2; exit 1; }
shift
while getopts "t:n" o; do case $o in t) TOOL=$OPTARG ;; n) DRY=1 ;; *) exit 1 ;; esac; done

ALLOW="" PING=yes
# shellcheck source=/dev/null
. "$RECIPE"
[[ -n "$ALLOW" ]] || { echo "recipe sets no ALLOW" >&2; exit 1; }

if [[ -z "$TOOL" ]]; then
  for t in ufw firewall-cmd nft iptables; do command -v "$t" >/dev/null && { TOOL=$t; break; }; done
  [[ -n "$TOOL" ]] || { echo "no firewall tool found; use -t with -n to just print" >&2; exit 1; }
fi
case "$TOOL" in firewall-cmd) TOOL=firewalld ;; nft) TOOL=nftables ;; esac
(( DRY )) || [[ $EUID -eq 0 ]] || { echo "run as root (or add -n)" >&2; exit 1; }

run()   { if (( DRY )); then echo "$*"; else "$@"; fi; }
is6()   { [[ $1 == *:* ]]; }
# "27015:27030/udp@10.0.0.0/8" -> PORT=27015:27030 PROTO=udp CIDR=10.0.0.0/8
parse() { local e=$1; CIDR=""; [[ $e == *@* ]] && CIDR=${e#*@}; e=${e%%@*}; PORT=${e%/*}; PROTO=${e#*/}; }

# ---------------------------------------------------------------- iptables
do_iptables() {
  local ipt icmp
  for ipt in iptables ip6tables; do
    icmp=icmp; [[ $ipt == ip6tables ]] && icmp=ipv6-icmp
    run $ipt -P INPUT ACCEPT; run $ipt -F INPUT          # open first; an error below can't lock us out
    run $ipt -A INPUT -i lo -j ACCEPT
    run $ipt -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    run $ipt -A INPUT -m conntrack --ctstate INVALID -j DROP
    [[ $PING == yes || $ipt == ip6tables ]] && run $ipt -A INPUT -p $icmp -j ACCEPT   # v6 needs ICMP for NDP
    for e in $ALLOW; do
      parse "$e"
      if [[ -n $CIDR ]]; then
        # A v4 CIDR only makes sense in iptables, a v6 one only in ip6tables.
        if is6 "$CIDR"; then [[ $ipt == ip6tables ]] || continue; else [[ $ipt == iptables ]] || continue; fi
        run $ipt -A INPUT -p $PROTO -s $CIDR --dport $PORT -j ACCEPT
      else
        run $ipt -A INPUT -p $PROTO --dport $PORT -j ACCEPT
      fi
    done
    run $ipt -P INPUT DROP; run $ipt -P FORWARD DROP
  done
  if command -v netfilter-persistent >/dev/null; then run netfilter-persistent save
  elif [[ -d /etc/iptables ]]; then
    if (( DRY )); then echo "iptables-save > /etc/iptables/rules.v4; ip6tables-save > /etc/iptables/rules.v6"
    else iptables-save > /etc/iptables/rules.v4; ip6tables-save > /etc/iptables/rules.v6; fi
  else echo "# NOT persisted: apt install iptables-persistent | dnf install iptables-services" >&2; fi
}

# ---------------------------------------------------------------- nftables
do_nftables() {
  local rules="" fam
  for e in $ALLOW; do
    parse "$e"
    if [[ -n $CIDR ]]; then fam=ip; is6 "$CIDR" && fam=ip6; rules+="    $fam saddr $CIDR $PROTO dport ${PORT/:/-} accept"$'\n'
    else rules+="    $PROTO dport ${PORT/:/-} accept"$'\n'; fi
  done
  local ping=""; [[ $PING == yes ]] && ping="    ip protocol icmp accept"$'\n'
  local conf
  conf=$(cat <<EOF
#!/usr/sbin/nft -f
# generated by fw.sh from $RECIPE
flush ruleset
table inet filter {
  chain input {
    type filter hook input priority 0; policy drop;
    iif lo accept
    ct state established,related accept
    ct state invalid drop
${ping}    meta l4proto ipv6-icmp accept
${rules}  }
  chain forward { type filter hook forward priority 0; policy drop; }
  chain output  { type filter hook output  priority 0; policy accept; }
}
EOF
)
  if (( DRY )); then echo "$conf"; return; fi
  echo "$conf" > /etc/nftables.conf        # what nftables.service loads at boot
  nft -f /etc/nftables.conf
  systemctl enable nftables >/dev/null 2>&1 || true
}

# ---------------------------------------------------------------- ufw
do_ufw() {
  [[ $PING == yes ]] || echo "# ufw: PING=no needs an edit to /etc/ufw/before.rules, skipping" >&2
  run ufw --force reset
  run ufw default deny incoming
  run ufw default allow outgoing
  for e in $ALLOW; do
    parse "$e"
    if [[ -n $CIDR ]]; then run ufw allow proto $PROTO from $CIDR to any port $PORT
    else run ufw allow $PORT/$PROTO; fi
  done
  run ufw --force enable
}

# ---------------------------------------------------------------- firewalld
do_firewalld() {
  local z=fw-recipe fam i
  run firewall-cmd -q --permanent --delete-zone=$z || true
  run firewall-cmd -q --permanent --new-zone=$z
  run firewall-cmd -q --permanent --zone=$z --set-target=DROP
  [[ $PING == yes ]] && run firewall-cmd -q --permanent --zone=$z --add-protocol=icmp
  run firewall-cmd -q --permanent --zone=$z --add-protocol=ipv6-icmp
  for e in $ALLOW; do
    parse "$e"
    if [[ -n $CIDR ]]; then
      fam=ipv4; is6 "$CIDR" && fam=ipv6
      run firewall-cmd -q --permanent --zone=$z --add-rich-rule="rule family=$fam source address=$CIDR port port=${PORT/:/-} protocol=$PROTO accept"
    else
      run firewall-cmd -q --permanent --zone=$z --add-port=${PORT/:/-}/$PROTO
    fi
  done
  # Move every interface, otherwise NetworkManager leaves them in "public".
  for i in /sys/class/net/*; do i=${i##*/}; [[ $i == lo ]] && continue; run firewall-cmd -q --permanent --zone=$z --change-interface=$i; done
  run firewall-cmd -q --set-default-zone=$z
  run firewall-cmd -q --reload
}

echo "# $TOOL <- $RECIPE   ALLOW: $ALLOW" >&2
"do_$TOOL"
